name: Build Xray

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Build xray for padavan'
        required: true
        default: 'build'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup golang version
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.2'

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt install upx git -y

    - name: Clone&Build source code
      id: build
      run: |
        git clone https://github.com/xtls/xray-core.git xray-core
        cd xray-core
        git checkout a58e20c81119e2a46d8975c3123e18f5dd63821e
        #cd xray-core/main
        cd main
        #GOOS=linux GOARCH=mipsle go build -o ../../xraybin/xray
        GOOS=linux GOARCH=mipsle go build -o ../../xraybin/xray -trimpath -ldflags "-s -w -buildid=" ./
        cd ../../xraybin
        #upx -9 xray
        shopt -s extglob
        rm -vrf !("xray")
        echo "xray=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name : Upload packages
      uses: actions/upload-artifact@main
      if: steps.build.outputs.status == 'success'
      with:
        name: xray-packages
        path: ${{ env.xray }}
    - name: Upload firmware to wenshushu
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wss --block 2621440 -s -p 64 --no-progress ${xray} 2>&1 | tee wenshushu.log
        echo "::warning file=wenshushu.cn::$(cat wenshushu.log | grep https | cut -f3 -d" ")"
        echo "Wenshushu_URL=$(cat wenshushu.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV
